-- Estructura de la tabla en H2
CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    second_last_name VARCHAR(100),
    age INTEGER,
    gender VARCHAR(10) NOT NULL,
    birth_date DATE NOT NULL,
    position VARCHAR(100) NOT NULL
);

-- Datos iniciales
INSERT INTO employees (first_name, last_name, age, gender, birth_date, position) VALUES
('John', 'Doe', 30, 'Male', '1993-05-07', 'Developer'),
('Jane', 'Smith', 28, 'Female', '1995-03-14', 'Designer'),
('Michael', 'Johnson', 35, 'Male', '1988-07-19', 'Manager'),
('Emily', 'Davis', 26, 'Female', '1997-11-03', 'HR Specialist'),
('Daniel', 'Martinez', 40, 'Male', '1983-01-22', 'Tech Lead'),
('Sophia', 'Lopez', 31, 'Female', '1992-06-30', 'Data Analyst'),
('David', 'Gonzalez', 29, 'Male', '1994-08-18', 'Business Analyst'),
('Isabella', 'Wilson', 27, 'Female', '1996-02-10', 'Marketing Specialist'),
('James', 'Anderson', 33, 'Male', '1990-04-05', 'Product Manager'),
('Ava', 'Thomas', 25, 'Female', '1998-09-16', 'Software Engineer'),
('Logan', 'Taylor', 34, 'Male', '1989-12-21', 'Architect'),
('Mia', 'Moore', 28, 'Female', '1995-10-10', 'Sales Representative'),
('Lucas', 'Jackson', 32, 'Male', '1991-05-17', 'QA Engineer'),
('Amelia', 'Martin', 24, 'Female', '1999-07-23', 'Intern'),
('Ethan', 'Lee', 30, 'Male', '1993-03-08', 'DevOps Engineer'),
('Harper', 'Perez', 26, 'Female', '1997-12-02', 'UI/UX Designer'),
('Oliver', 'White', 36, 'Male', '1987-08-25', 'Operations Manager'),
('Ella', 'Clark', 29, 'Female', '1994-06-19', 'HR Manager'),
('William', 'Rodriguez', 31, 'Male', '1992-10-28', 'Frontend Developer'),
('Avery', 'Lewis', 27, 'Female', '1996-11-14', 'Backend Developer'),
('Benjamin', 'Walker', 38, 'Male', '1985-04-30', 'Solutions Architect'),
('Scarlett', 'Hall', 25, 'Female', '1998-01-09', 'Content Writer'),
('Henry', 'Allen', 33, 'Male', '1990-07-06', 'Network Engineer'),
('Sofia', 'Young', 28, 'Female', '1995-03-25', 'Accountant'),
('Jack', 'King', 37, 'Male', '1986-09-12', 'IT Manager');